/* Planet + quiz data for Orbit Explorer.
   Orbital radii are in "world units" (scaled, not to real scale). */

const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    emoji: "🟡",
    color: "#b8a89a",
    radius: 5,
    orbit: 70,
    periodYears: 0.24,
    type: "Terrestrial planet",
    distance: "57.9 million km",
    diameter: "4,879 km",
    year: "88 Earth days",
    day: "59 Earth days",
    moons: "0",
    blurb:
      "The smallest planet and the closest to the Sun. It has almost no atmosphere, scorching days, and freezing nights.",
  },
  {
    id: "venus",
    name: "Venus",
    emoji: "🌕",
    color: "#e8c98b",
    radius: 7,
    orbit: 95,
    periodYears: 0.62,
    type: "Terrestrial planet",
    distance: "108.2 million km",
    diameter: "12,104 km",
    year: "225 Earth days",
    day: "243 Earth days (rotates backwards)",
    moons: "0",
    blurb:
      "Earth's toxic twin. Its thick carbon-dioxide atmosphere traps heat, making it the hottest planet in the Solar System.",
  },
  {
    id: "earth",
    name: "Earth",
    emoji: "🌍",
    color: "#4aa8ff",
    radius: 8,
    orbit: 125,
    periodYears: 1,
    type: "Terrestrial planet",
    distance: "149.6 million km",
    diameter: "12,742 km",
    year: "365.25 days",
    day: "23.9 hours",
    moons: "1 — The Moon",
    blurb:
      "Our home. The only known world with liquid surface water, oxygen-rich air, and life. It is the launch point for all our missions.",
  },
  {
    id: "mars",
    name: "Mars",
    emoji: "🔴",
    color: "#e2703a",
    radius: 6,
    orbit: 160,
    periodYears: 1.88,
    type: "Terrestrial planet",
    distance: "227.9 million km",
    diameter: "6,779 km",
    year: "687 Earth days",
    day: "24.6 hours",
    moons: "2 — Phobos & Deimos",
    blurb:
      "The Red Planet. Iron oxide dust gives it a rusty colour. It hosts polar ice caps and has been a top target for robotic explorers.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    emoji: "🟠",
    color: "#e0a86b",
    radius: 14,
    orbit: 210,
    periodYears: 11.86,
    type: "Gas giant",
    distance: "778.5 million km",
    diameter: "139,820 km",
    year: "11.9 Earth years",
    day: "9.9 hours",
    moons: "95 known",
    blurb:
      "The largest planet — more than twice the mass of all the others combined. Its Great Red Spot is a storm bigger than Earth.",
  },
  {
    id: "saturn",
    name: "Saturn",
    emoji: "🪐",
    color: "#e8cd9a",
    radius: 12,
    orbit: 260,
    periodYears: 29.46,
    ring: true,
    type: "Gas giant",
    distance: "1.42 billion km",
    diameter: "116,460 km",
    year: "29.4 Earth years",
    day: "10.7 hours",
    moons: "146 known",
    blurb:
      "The ringed jewel of the Solar System. Its spectacular rings are made of ice and rock and are only about 10 metres thick in places.",
  },
  {
    id: "uranus",
    name: "Uranus",
    emoji: "🔵",
    color: "#9fe3ea",
    radius: 10,
    orbit: 315,
    periodYears: 84.01,
    type: "Ice giant",
    distance: "2.87 billion km",
    diameter: "50,724 km",
    year: "84 Earth years",
    day: "17.2 hours (retrograde)",
    moons: "28 known",
    blurb:
      "The sideways planet — it rotates on its side, possibly knocked over by a giant impact. It is the coldest planet in the Solar System.",
  },
  {
    id: "neptune",
    name: "Neptune",
    emoji: "🔷",
    color: "#5a7cfa",
    radius: 10,
    orbit: 360,
    periodYears: 164.8,
    type: "Ice giant",
    distance: "4.50 billion km",
    diameter: "49,244 km",
    year: "165 Earth years",
    day: "16.1 hours",
    moons: "16 known",
    blurb:
      "The most distant planet. It has the strongest winds in the Solar System and was the first planet found with mathematics before telescopes.",
  },
];

const QUIZ_QUESTIONS = [
  {
    q: "Which planet is known as the Red Planet?",
    options: ["Mars", "Venus", "Mercury", "Jupiter"],
    answer: 0,
    explain: "Iron oxide (rust) on the Martian surface gives it a reddish colour.",
  },
  {
    q: "Which is the largest planet in the Solar System?",
    options: ["Saturn", "Neptune", "Jupiter", "Uranus"],
    answer: 2,
    explain: "Jupiter is over twice as massive as all the other planets combined.",
  },
  {
    q: "Which planet is sometimes called Earth's twin?",
    options: ["Mars", "Venus", "Mercury", "Neptune"],
    answer: 1,
    explain: "Venus is similar in size and gravity to Earth, but its atmosphere is a boiling greenhouse.",
  },
  {
    q: "Which planet is the closest to the Sun?",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    answer: 2,
    explain: "Mercury orbits the Sun at an average distance of 57.9 million km.",
  },
  {
    q: "Which planet has the most prominent and beautiful rings?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    answer: 1,
    explain: "Saturn's icy rings stretch for hundreds of thousands of kilometres.",
  },
  {
    q: "What is the Great Red Spot?",
    options: ["A volcano", "A huge storm", "A crater", "An ocean"],
    answer: 1,
    explain: "It is a giant storm on Jupiter that has lasted for hundreds of years.",
  },
  {
    q: "Which planet has a day longer than its year?",
    options: ["Venus", "Mars", "Earth", "Saturn"],
    answer: 0,
    explain: "Venus spins so slowly that one day there lasts longer than one orbit around the Sun.",
  },
  {
    q: "Which planet rotates on its side?",
    options: ["Mercury", "Saturn", "Uranus", "Mars"],
    answer: 2,
    explain: "Uranus tilts about 98°, likely due to a massive ancient collision.",
  },
  {
    q: "How many planets are in our Solar System?",
    options: ["7", "8", "9", "10"],
    answer: 1,
    explain: "There are eight planets; Pluto is a dwarf planet.",
  },
  {
    q: "What is the Sun mostly made of?",
    options: ["Oxygen and carbon", "Iron and nickel", "Hydrogen and helium", "Lava and rock"],
    answer: 2,
    explain: "The Sun is a ball of plasma, about 74% hydrogen and 24% helium.",
  },
  {
    q: "Which planet is the windiest, with speeds over 2,000 km/h?",
    options: ["Jupiter", "Neptune", "Earth", "Mars"],
    answer: 1,
    explain: "Neptune's supersonic winds are the fastest in the Solar System.",
  },
  {
    q: "Which planet has the most confirmed moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    answer: 1,
    explain: "Saturn has 146 known moons, edging out Jupiter's 95.",
  },
  {
    q: "Which is the smallest planet in the Solar System?",
    options: ["Mars", "Venus", "Mercury", "Pluto"],
    answer: 2,
    explain: "Mercury is smaller than Earth's Moon and is the smallest of the eight planets.",
  },
  {
    q: "The Sun is a...",
    options: ["Planet", "Star", "Moon", "Comet"],
    answer: 1,
    explain: "The Sun is a medium-sized yellow dwarf star at the centre of our system.",
  },
  {
    q: "Which planet is the coldest?",
    options: ["Neptune", "Mars", "Mercury", "Uranus"],
    answer: 0,
    explain: "Neptune's cloud tops dip to about -218 °C, the coldest planetary atmosphere.",
  },
  {
    q: "Which planet is our nearest planetary neighbour?",
    options: ["Mars", "Venus", "Mercury", "Jupiter"],
    answer: 1,
    explain: "On average, Venus comes closer to Earth than any other planet.",
  },
];
